### ISSUE TITLE
BUG/DOC: DataFrame.values return type when uint64 is mixed with signed int types

### ISSUE THREAD

**Issue by kawochen** [pandas-dev/pandas#10364]
`DataFrame.values`' doc mentions type promotion but leaves out that when `uint64` is mixed with signed `int` types, the return type is `int64`, which can be surprising.  Perhaps consider returning `dtype(object)` in `internals._interleaved_dtype` when `uint64` and signed `int`s are present?

**Comment by jreback** [comment]
so this could certainly have an expanded doc-string (and maybe a link to ``np.find_common_type`` in the ``Notes`` section, though it uses custom logic to avoid *always* upcasting to ``object``).

Certainly ``_interleaved_dtype`` could be improved, though general support for ``uint64`` is pretty limited in general (e.g. using it in numerics will automatically make this ``object``). So in reaility it is a type to be avoided, unless you really really have large ints.

**Comment by petehuang** [comment]
This was addressed via #13917 and should be closed. Thanks to @sstanovnik, @sinhrks and @jreback for the fix and @kawochen for the issue!

**Comment by jreback** [comment]
@gfyoung just noticed this a uint64 issue!

**Comment by gfyoung** [comment]
Hmm they seem to be everywhere 😀.   Should double check that it's resolved.

**Comment by gfyoung** [comment]
@jreback : Okay, this is not resolved as I had thought.  So when we call `DataFrame.values`, it defaults to `float64` when `int` and `uint` are encountered together.  I think we're sticking with `object` now?

**Comment by jorisvandenbossche** [comment]
This was indeed addressed in the linked PR, test has changed here: https://github.com/pandas-dev/pandas/pull/13917/files#diff-137c96159899927aedd9b37f0f7dddf8R117

Returning float is following the numpy rules.

> I think we're sticking with object now?

What do you mean exactly? That it should return object? Before (< 0.19.0), it returned int64, now it returns float64. 
Which I think is correct, and this issue can just be closed

Current `DataFrame.values` docs also seem to correctly mention the float return type (minus a typo :-)):

```
In [75]: pd.DataFrame.values?
Type:        property
String form: <property object at 0x7f7253dd2408>
Docstring:  
Numpy representation of NDFrame

Notes
-----
The dtype will be a lower-common-denominator dtype (implicit
upcasting); that is to say if the dtypes (even of numeric types)
are mixed, the one that accommodates all will be chosen. Use this
with care if you are not dealing with the blocks.

e.g. If the dtypes are float16 and float32, dtype will be upcast to
float32.  If dtypes are int32 and uint8, dtype will be upcast to
int32. By numpy.find_common_type convention, mixing int64 and uint64
will result in a flot64 dtype.
```

**Comment by jorisvandenbossche** [comment]
Fixed by https://github.com/pandas-dev/pandas/pull/13917

**Comment by gfyoung** [comment]
@jorisvandenbossche : The reason why I asked about `object` is because that is what we return when we call something like `to_numeric` and we have mixed `uint` and signed `int`.  I'm always wary of `float` because it destroys precision on the `uint` values, that's all.
