### ISSUE TITLE
`concat` without `sort` in groupby.py code raises FutureWarning

### ISSUE THREAD

**Issue by aloukina** [pandas-dev/pandas#25174]
#### Problem description

There are several calls to `concat` in `groupby.py` that do not pass the `sort` argument. This raises FutureWarning when the function is exectuted. For example:

```
pandas/core/groupby/groupby.py:1105: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version 
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  result = concat(values, axis=self.axis)
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 40.6.3
Cython: None
numpy: 1.14.2
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.2.0
xlsxwriter: None
lxml: None
bs4: 4.7.1
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
Can you share the code you have to reproduce? I see you are using v0.23.4 this has most likely been fixed in more recent release

**Comment by aloukina** [comment]
Here is the corresponding line in `master`: https://github.com/pandas-dev/pandas/blob/e3b095074c5c3b29ec25a994cd204349b872d961/pandas/core/groupby/groupby.py#L887

**Comment by blu3r4y** [comment]
There are still a lot of calls that are missing the `sort` argument in [`groupby.py`](https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py) on master, triggering internal warnings.

The last warning I got in 0.25.1 was here: (it's still the same line as mentioned by @aloukina)
https://github.com/pandas-dev/pandas/blob/760c65407c3362e3c4660207ea447b90d035f2f5/pandas/core/groupby/groupby.py#L937

**Comment by blu3r4y** [comment]
@TomAugspurger sure! (tested with `pandas==0.25.1`)

```
import pandas as pd

df = pd.DataFrame({
    "group": ["a", "b", "c"],
    "value": [1, 2, 3]
})

df.groupby("group")["value"].apply(pd.DataFrame)
```

This yields the `FutureWarning` in `groupby.py:937`
https://github.com/pandas-dev/pandas/blob/81fe56a53a67095979764581aca0cab623b941eb/pandas/core/groupby/groupby.py#L937

**Comment by TomAugspurger** [comment]
Thanks! That one is coming from
https://github.com/pandas-dev/pandas/blob/c4489cbfa5f93e69301486e1ef867caed9f4eb9e/pandas/core/groupby/groupby.py#L939
.

Anyone interested in making a PR?

**Comment by jbrockmendel** [comment]
Is this closed by #29786?

**Comment by jbrockmendel** [comment]
I don't see a warning in master, so closing as closed by #29786.  Feel free to ping if the issue reappears and we can re-open.
