### ISSUE TITLE
BUG: `Series.replace` doesn't update `CategoricalDtype` when `inplace=True` in pandas-2.0

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#53358]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [1]: import pandas as pd

In [2]: s = pd.Series(["one", "two", "three"], dtype="category")

In [3]: s
Out[3]: 
0      one
1      two
2    three
dtype: category
Categories (3, object): ['one', 'three', 'two']

In [4]: new_s = s.replace(to_replace="one", value="two")

In [5]: new_s
Out[5]: 
0      two
1      two
2    three
dtype: category
Categories (2, object): ['three', 'two']

In [6]: new_s.dtype
Out[6]: CategoricalDtype(categories=['three', 'two'], ordered=False)     # Correct

In [7]: s.replace(to_replace="one", value="two", inplace=True)

In [8]: s
Out[8]: 
0      two
1      two
2    three
dtype: category
Categories (2, object): ['three', 'two']          # Correct __repr__ output

In [9]: s.dtype
Out[9]: CategoricalDtype(categories=['one', 'three', 'two'], ordered=False). # BUG: Incorrect dtype, dtype used to be updated pre pandas-2.0
```

### Issue Description

When we replace values in a categorical Series, with `inplace=True`, the dtype is not being updated.

### Expected Behavior

```python
In [9]: s.dtype
Out[9]: CategoricalDtype(categories=['three', 'two'], ordered=False)
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.10.11.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-76-generic
Version          : #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.1
numpy            : 1.23.5
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : 0.29.34
pytest           : 7.3.1
hypothesis       : 6.75.3
sphinx           : 5.3.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2023.5.0
gcsfs            : None
matplotlib       : None
numba            : 0.56.4
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2023.5.0
scipy            : 1.10.1
snappy           : 
sqlalchemy       : 2.0.15
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by mroeschke** [comment]
This looks to be fixed on main (and I think will be fixed in 2.1). Could use a unit test

```python
In [1]: In [1]: import pandas as pd
   ...: 
   ...: In [2]: s = pd.Series(["one", "two", "three"], dtype="category")

In [2]: s.replace(to_replace="one", value="two", inplace=True)

In [3]: s
Out[3]: 
0      two
1      two
2    three
dtype: category
Categories (2, object): ['three', 'two']

In [4]: s.dtype
Out[4]: CategoricalDtype(categories=['three', 'two'], ordered=False, categories_dtype=object)
```

**Comment by Bsvelandiac** [comment]
take

**Comment by Bsvelandiac** [comment]
take

**Comment by yusharth** [comment]
Hey @Bsvelandiac can I help you with this task?

**Comment by happyvignesh** [comment]
Hi @galipremsagar,
Thanks for the clear reproducible example.
I tried to reproduce it however I do get different output when I print Series.dtype.(i.e. it prints only "category" ).


`s.replace(to_replace="one", value="two", inplace=True)
print('value of s after replace')
print(s)
print(s.dtype)

# Out[8]:
value of s after replace
# 0      two
# 1      two
# 2    three
# dtype: category
# Categories (2, object) : ['three', 'two']
# category
`

please refer the below details.
pandas version: 2.0.1
Branch: main

**Comment by galipremsagar** [comment]
> ```python
> s.replace(to_replace="one", value="two", inplace=True)
> ```

@happyvignesh Like @mroeschke pointed here, it's now fixed in `2.0.2` too but probably needs some pytests in pandas code-base.

**Comment by aadeshmodak13** [comment]
it's now fixed in 2.0.2

**Comment by tpackard1** [comment]
Hi @mroeschke 

I was looking into writing the pytests for this bug. In your comment above https://github.com/pandas-dev/pandas/issues/53358#issuecomment-1560122484 and other's comments they say it is fixed on `2.0.2` or main, but when I did a `pip install --upgrade pandas` and did the following code:

```
 >>> import pandas as pd
>>> print(pd.__version__)
2.0.2
>>> s = pd.Series(["one", "two", "three"], dtype="category")
>>> s
0      one
1      two
2    three
dtype: category
Categories (3, object): ['one', 'three', 'two']
>>> s.replace(to_replace="one", value="two", inplace=True)
>>> s
0      two
1      two
2    three
dtype: category
Categories (2, object): ['three', 'two']
>>> s.dtype
CategoricalDtype(categories=['one', 'three', 'two'], ordered=False)
```
I still get the error as mentioned originally. Should I be pulling the source code for main or `2.0.2` from another source or should I just be writing the test for `2.1`? Sorry for the ignorant question still a noob to contributing to pandas.

**Comment by mohammedouahman** [comment]
Good to hear that!!

**Comment by natmokval** [comment]
Hi @Bsvelandiac , I'd like to create a pr for this issue if you don't mind.
