### ISSUE TITLE
BUG: `assert_frame_equals` fails when `MultiIndex` elements are `None`

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#54521]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
df = DataFrame({
    "Currency": ["USD", "USD", "USD"],
    "Collateral": [None, None, None],
    "Payment": [dt(2023, 1, 1), dt(2023, 1, 1), dt(2023, 2, 1)],
    "Cashflow": [100.0, 100.0, 200.0],
})
gf = df.groupby(["Currency", "Collateral", "Payment"], dropna=False)
       .sum()
       .unstack([0, 1])
       .droplevel(0, axis=1)
```

### Issue Description

![Screenshot 2023-08-13 at 09 02 18](https://github.com/pandas-dev/pandas/assets/24256554/4f94d9da-6a0c-49b3-84c8-476a5fe0ea74)

This regards `assert_frame_equal` as part of a test suite.

The first problem with regards to testing `gf` is that I cannot create a `MultiIndex` and instantiate its `dtypes` directly.

```python
expected = DataFrame(
    [200.0, 200.0],
    columns=MultiIndex.from_tuples([("USD", np.nan)], names=["Currency", "Collateral"]),
    index=[dt(2023, 1, 1), dt(2023, 2, 1)]
)
assert_frame_equal(gf, expected, atol=1e-5)

>> Traceback..
>       assert_attr_equal("dtype", left, right, obj=obj)
E       AssertionError: MultiIndex level [1] are different
E       
E       Attribute "dtype" are different
E       [left]:  float64
E       [right]: object
```

But I can manipulate it like this:
```python
expected = DataFrame(
    [200.0, 200.0],
    columns=MultiIndex.from_arrays([
        Index(["USD"], name="Currency"), 
        Index([None], name="Collateral", dtype="float64")
    ]),
    index=[dt(2023, 1, 1), dt(2023, 2, 1)]
)
assert_frame_equal(gf, expected, atol=1e-5)

>> Traceback..
>       assert_frame_equal(result, expected, atol=1e-4)
E       AssertionError: DataFrame.iloc[:, 0] (column name="('USD', nan)") are different
E       
E       Attribute "name" are different
E       [left]:  ('USD', nan)
E       [right]: ('USD', nan)
```

There is a NA check for `name` but apparently it doesn't nest within the tuple so that this fails.

### Expected Behavior

Should assert `True`. Na nest should be checked and works fine.

### Installed Versions

<details>

2.0.3

</details>

**Comment by phofl** [comment]
Is groupby necessary to reproduce? We fixed some bugs in the MultiIndex construction before the 2.1 rc came out

**Comment by attack68** [comment]
when i next get chance will check on main or rc.

**Comment by chaoyihu** [comment]
> Is groupby necessary to reproduce?

The intention here is to assert equal on two `MultiIndex` objects of float type. I think the role of groupby here is to circumvent initializing `MultiIndex` directly with NA values, which will result in an inferred `object` dtype.

> We fixed some bugs in the MultiIndex construction before the 2.1 rc came out

This still exists on main as of 1165859bd147a0b4afa66663ad66078beb91f4fe. The assertion failure says:
```
Attribute "name" are different
[left]:  ('USD', nan)
[right]: ('USD', nan)
```
because they are not the same `nan`:
```
print(gf.columns)
print(gf.columns.levels)
print(gf.columns.codes)
print("===========")
print(expected.columns)
print(expected.columns.levels)
print(expected.columns.codes)
print("===========")
print(gf.columns == expected.columns)
assert_frame_equal(gf, expected)
```
```
MultiIndex([('USD', nan)],
           names=['Currency', 'Collateral'])
[['USD'], [nan]]  # here it is a float nan
[[0], [0]]
===========
MultiIndex([('USD', nan)],
           names=['Currency', 'Collateral'])
[['USD'], []]  # here it is an empty list
[[0], [-1]]
===========
[False]
AssertionError: DataFrame.iloc[:, 0] (column name="('USD', nan)") are different
Attribute "name" are different
[left]:  ('USD', nan)
[right]: ('USD', nan)
```

The fix should be similar to https://github.com/pandas-dev/pandas/pull/59069, by giving NA values a location index of -1 in `levels` attributes of `MultiIndex` instance when is it created from `groupby`.
