### ISSUE TITLE
BUG: issues with plotting horizontal bar chart

### ISSUE THREAD

**Issue by 2332575Y** [pandas-dev/pandas#58042]
### Pandas version checks

- [x] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)

df = pd.DataFrame(
    {
        "A" : np.random.randint(10, size = 5),
        "B" : np.random.randint(10, size = 5),
        "C" : np.random.randint(10, size = 5)
    }
).T

df.plot(
    kind="bar",
    stacked=True,
    legend=False,
    width=0.8
)

plt.show()

df.plot(
    kind="barh",
    stacked=True,
    legend=False,
    height=0.8
)

plt.show()
```

### Issue Description

When using a normal bar chart, `width` can be adjusted to reduce the gap between bars, however adjusting `height` for horizontal bar charts causes duplicate height values to be passed, causing:

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    Cell In[1], line 24
         15 df.plot(
         16     kind="bar",
         17     stacked=True,
         18     legend=False,
         19     width=0.8
         20 )
         22 plt.show()
    ---> 24 df.plot(
         25     kind="barh",
         26     stacked=True,
         27     legend=False,
         28     height=0.8
         29 )
         31 plt.show()
    
    File ~\Anaconda3\envs\py310\lib\site-packages\pandas\plotting\_core.py:1030, in PlotAccessor.__call__(self, *args, **kwargs)
       1027             label_name = label_kw or data.columns
       1028             data.columns = label_name
    -> 1030 return plot_backend.plot(data, kind=kind, **kwargs)
    
    File ~\Anaconda3\envs\py310\lib\site-packages\pandas\plotting\_matplotlib\__init__.py:71, in plot(data, kind, **kwargs)
         69         kwargs["ax"] = getattr(ax, "left_ax", ax)
         70 plot_obj = PLOT_CLASSES[kind](data, **kwargs)
    ---> 71 plot_obj.generate()
         72 plot_obj.draw()
         73 return plot_obj.result
    
    File ~\Anaconda3\envs\py310\lib\site-packages\pandas\plotting\_matplotlib\core.py:501, in MPLPlot.generate(self)
        499 self._compute_plot_data()
            500 fig = self.fig
        --> 501 self._make_plot(fig)
            502 self._add_table()
            503 self._make_legend()
        
        File ~\Anaconda3\envs\py310\lib\site-packages\pandas\plotting\_matplotlib\core.py:1934, in BarPlot._make_plot(self, fig)
           1932 start = np.where(mask, pos_prior, neg_prior) + self._start_base
           1933 w = self.bar_width / 2
        -> 1934 rect = self._plot(
           1935     ax,
           1936     self.ax_pos + w,
           1937     y,
           1938     self.bar_width,
           1939     start=start,
           1940     label=label,
           1941     log=self.log,
           1942     **kwds,
           1943 )
           1944 pos_prior = pos_prior + np.where(mask, y, 0)
           1945 neg_prior = neg_prior + np.where(mask, 0, y)
        
        File ~\Anaconda3\envs\py310\lib\site-packages\pandas\plotting\_matplotlib\core.py:2018, in BarhPlot._plot(cls, ax, x, y, w, start, log, **kwds)
           2007 @classmethod
           2008 def _plot(  # type: ignore[override]
           2009     cls,
           (...)
           2016     **kwds,
           2017 ):
        -> 2018     return ax.barh(x, y, w, left=start, log=log, **kwds)
        
        TypeError: Axes.barh() got multiple values for argument 'height'

### Expected Behavior

Height of bars to update correctly 

### Installed Versions

<details>
INSTALLED VERSIONS<br>
------------------<br>
commit                : bdc79c146c2e32f2cab629be240f01658cfb6cc2<br>
python                : 3.10.13.final.0<br>
python-bits           : 64<br>
OS                    : Windows<br>
OS-release            : 10<br>
Version               : 10.0.19045<br>
machine               : AMD64<br>
processor             : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel<br>
byteorder             : little<br>
LC_ALL                : None<br>
LANG                  : None<br>
LOCALE                : English_United States.1252<br>

pandas                : 2.2.1
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 68.0.0
pip                   : 24.0
Cython                : 3.0.9
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.1.0
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.3
IPython               : 8.22.2
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : 1.3.8
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.3.1
gcsfs                 : None
matplotlib            : 3.8.3
numba                 : None
numexpr               : 2.9.0
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.12.0
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
</details>

**Comment by swalehmwadime** [comment]
### Bug Resolution

#### Description:
Resolved the issue where a TypeError occurred when adjusting the `height` parameter for horizontal bar charts (`kind="barh"`) in pandas.

#### Resolution:
Removed the `height` parameter from the `plot` method call when plotting horizontal bar charts.



```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)

df = pd.DataFrame(
    {
        "A": np.random.randint(10, size=5),
        "B": np.random.randint(10, size=5),
        "C": np.random.randint(10, size=5)
    }
).T

df.plot(
    kind="bar",
    stacked=True,
    legend=False,
    width=0.8
)

plt.show()

df.plot(
    kind="barh",
    stacked=True,
    legend=False  # Removed the height parameter here
)

plt.show()
```

#### Expected Behavior:
The horizontal bar chart should plot correctly without raising a TypeError when adjusting the height parameter.

#### Additional Notes:
- The bug fix has been tested and verified.
- The code works as expected without causing any errors.

---

This resolution addresses the TypeError issue encountered when adjusting the height parameter for horizontal bar charts in pandas.

**Comment by 2332575Y** [comment]
@swalehmwadime How does this fix the bug? it only hides the problem. How does it make sense that changing the width of vertical bars works as expected, but changing height of horizontal bars throws an error instead of resizing them? Also what you addressed in your expected behavior DOES NOT COVER RESIZING THE BARS which is what the issue was raised for and the expected behavior clearly states: "Height of bars to update correctly"

**Comment by swalehmwadime** [comment]
The error message indicates that the barh function is receiving multiple values for the height argument. This is because the df DataFrame is transposed in the code, so the barh function is trying to plot the rows as bars, but there is no single height value for each row.

**Comment by 2332575Y** [comment]
But this is exactly what I'm trying to achieve, is there not a way to transpose and still change the bar heights? I tried creating a copy of the data frame, but that didn't change anything. I still don't understand why this is a limitation
