### ISSUE TITLE
BUG: index.union fails at DST boundary

### ISSUE THREAD

**Issue by anttimc** [pandas-dev/pandas#62915]
### Pandas version checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
index=pd.date_range('2025-10-25', '2025-10-26', freq='d', tz='Europe/Helsinki')
index2=pd.date_range('2025-10-25', '2025-10-28', freq='d', tz='Europe/Helsinki')
index.union(index2)
```

### Issue Description

index union fails when one index ends when day-light saving time ends and the other index contains timestamps after the transition.

The error comes from assert in  pandas/core/indexes/datetimelike.py", line 703, in _fast_union
`
    assert dates._freq == self.freq  # type: ignore[union-attr]
`

After debugging the root cause is the following check when concatenating the indices
https://github.com/pandas-dev/pandas/blob/54c26ec4d247097928320a7a77ba03c627a91b19/pandas/core/arrays/datetimelike.py#L2386

When that check fails, like it does in the example, the frequency of the index is set  None resulting in failing assert in `_fast_union`

### Expected Behavior

The index union succeeds

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 9c8bc3e55188c8aff37207a74f1dd144980b8874
python                : 3.13.5
python-bits           : 64
OS                    : Linux
OS-release            : 6.14.4-300.fc42.x86_64
Version               : #1 SMP PREEMPT_DYNAMIC Fri Apr 25 15:43:38 UTC 2025
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.3.3
numpy                 : 2.2.6
pytz                  : 2025.2
dateutil              : 2.9.0.post0
pip                   : 25.2
Cython                : None
sphinx                : 8.2.3
IPython               : 9.4.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.13.4
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : 6.136.9
gcsfs                 : None
jinja2                : 3.1.6
lxml.etree            : None
matplotlib            : 3.10.5
numba                 : 0.61.2
numexpr               : 2.10.2
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : 2.9.10
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : 8.4.1
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.16.0
sqlalchemy            : 2.0.42
tables                : 3.10.2
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : 0.23.0
tzdata                : 2025.2
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment]
I get the correct output on main.

```
DatetimeIndex(['2025-10-25 00:00:00+03:00', '2025-10-26 00:00:00+03:00',
               '2025-10-27 00:00:00+02:00', '2025-10-28 00:00:00+02:00'],
              dtype='datetime64[ns, Europe/Helsinki]', freq='D')
```

We should run a git bisect to see where this was fixed and determine if a test should be added.

**Comment by rhshadrach** [comment]
I'm seeing this was fixed by

```
commit 1bd183007b2dded1c712afb29ca90611908ac87e
Author: jbrockmendel
Date:   Mon Aug 11 10:29:46 2025 -0700

    API: offsets.Day is always calendar-day (#61985)
```

I'm not seeing a test there for union. Could use a test.

cc @jbrockmendel

**Comment by csreddy98** [comment]
@rhshadrach, I would like to take up this issue and add test cases for it. could you please assign this to me?

**Comment by rhshadrach** [comment]
@csreddy98 - we are no longer assigning issues as they go stale. Leaving a comment that you're working on this is sufficient!

**Comment by Arjundas08** [comment]
Hi! I'm new to contributing here and would love to add the regression test for this. I see from the comment above that issues aren't formally assigned, but I wanted to let you know I'm starting on it. Thanks!

**Comment by yashwantbezawada** [comment]
Hi @rhshadrach,

I wanted to clarify the status of this bug. After testing on the current main branch (commit 564197951e), **the bug still exists** and is not fixed by #61985.

## Reproduction on main branch:
```python
import pandas as pd
index1 = pd.date_range('2025-10-25', '2025-10-26', freq='d', tz='Europe/Helsinki')
index2 = pd.date_range('2025-10-25', '2025-10-28', freq='d', tz='Europe/Helsinki')
result = index1.union(index2)  # AssertionError
```

The error occurs in `pandas/core/arrays/datetimelike.py` at line 2386 in the `_concat_same_type` method:
```python
if all(pair[0][-1] + obj.freq == pair[1][0] for pair in pairs):
```

## Why #61985 didn't fix this:

The commit `1bd183007b` made `Day` offsets consistently represent 24 hours, but it didn't address the DST comparison issue in `_concat_same_type`. When comparing:
- `pair[0][-1] + obj.freq` = `2025-10-27 00:00+03:00` (naive addition)
- `pair[1][0]` = `2025-10-27 00:00+02:00` (actual value after DST)

These are not equal due to different UTC offsets, even though they represent consecutive days.

## My PR (#63017):

I've submitted a fix that:
1. For Tick frequencies: Compares UTC nanoseconds directly (`pair[1][0]._value - pair[0][-1]._value == freq_nanos`)
2. For non-Tick frequencies: Falls back to original comparison
3. Includes a regression test

The issue needs both a **bug fix** (not just a test), which is what PR #63017 provides.

@csreddy98 @Arjundas08 - I see you both expressed interest in working on this. My apologies for the overlap! Happy to collaborate or defer if you're actively working on it.

**Comment by rhshadrach** [comment]
> result = index1.union(index2)  # AssertionError

I do not get an error on main. Can you post the output of `pd.show_versions()`.

**Comment by yashwantbezawada** [comment]
@rhshadrach You're absolutely right - I apologize for the confusion!

I was testing with **pandas 2.3.3** (the latest released version from pip), where the bug still exists:

```
pandas                : 2.3.3
commit                : 9c8bc3e55188c8aff37207a74f1dd144980b8874
```

The bug is indeed **fixed on the main development branch** by commit `1bd183007b` as you identified. I should have built pandas from source to test against main properly.

I'll close PR #63017 since the fix is already in main. The issue only affects the 2.3.x release series.

Thank you for catching this!

**Comment by dohrisalim** [comment]
I can fix this daylight saving time boundary bug in index.union(). I understand the issue occurs in the frequency detection logic during index concatenation when one DatetimeIndex ends at a DST transition. I'll examine the _fast_union() implementation, fix the AssertionError, and add comprehensive test coverage for timezone edge cases.

**Comment by liudehua777** [comment]
Hi! I'd like to help improve the documentation for MultiIndex.swaplevel default argument values explanation.I'd like to collaborate on this issue for testing or other things!

**Comment by antznette1** [comment]
I’d like to work on this issue. I’ll start with a failing (xfail) test for `DatetimeIndex.union` across a DST boundary and follow up with a minimal fix if straightforward.
