### ISSUE TITLE
Can't slice float indices, but can slice integer indices?

### ISSUE THREAD

**Issue by mrjbq7** [pandas-dev/pandas#7501]
Using pandas 0.14, the slicing changed strangely.  I can slice rows using start/end with an integer index, but not a float index:

``` python
In [18]: df = pandas.DataFrame(np.random.randn(10, 5), index=np.arange(10, 20))

In [19]: df
Out[19]: 
           0         1         2         3         4
10 -1.878123 -0.581537  0.189536  0.173014  0.132059
11  1.229246 -0.988689  0.632404  0.939126 -0.186367
12  0.376735  0.329723  1.480293 -0.209164  0.080897
13  0.461558  0.303541 -0.669196 -1.032077  1.634512
14 -0.972455  0.657357 -0.566609  0.154165 -0.561543
15 -2.502244  1.022540 -1.019376 -0.934582  1.751852
16 -1.875567  0.504288 -0.524922  0.048277 -1.587904
17  0.636652  0.441224 -1.391552  0.650876  0.374673
18 -1.503102  0.822411  1.776667 -0.879583  1.035291
19 -0.620467  0.319855 -0.779280 -0.168827  0.502470

In [20]: df[3:5]
Out[20]: 
           0         1         2         3         4
13  0.461558  0.303541 -0.669196 -1.032077  1.634512
14 -0.972455  0.657357 -0.566609  0.154165 -0.561543

In [21]: df.index = [float(x) for x in df.index]

In [22]: df
Out[22]: 
           0         1         2         3         4
10 -1.878123 -0.581537  0.189536  0.173014  0.132059
11  1.229246 -0.988689  0.632404  0.939126 -0.186367
12  0.376735  0.329723  1.480293 -0.209164  0.080897
13  0.461558  0.303541 -0.669196 -1.032077  1.634512
14 -0.972455  0.657357 -0.566609  0.154165 -0.561543
15 -2.502244  1.022540 -1.019376 -0.934582  1.751852
16 -1.875567  0.504288 -0.524922  0.048277 -1.587904
17  0.636652  0.441224 -1.391552  0.650876  0.374673
18 -1.503102  0.822411  1.776667 -0.879583  1.035291
19 -0.620467  0.319855 -0.779280 -0.168827  0.502470

In [23]: df[3:5]
Out[23]: 
Empty DataFrame
Columns: [0, 1, 2, 3, 4]
Index: []

In [24]: df.index
Out[24]: Float64Index([10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0], dtype='float64')

In [25]: pandas.__version__
Out[25]: '0.14.0'
```

Was this an intentional change, or a bug?

**Comment by jreback** [comment]
I believe most of the oddness was fixed in 0.18.0 for the float slicing fixup. so going to revisit this.

**Comment by jorisvandenbossche** [comment]
@jreback What do you mean with 'revisit'? I don't think anything has changed to the original issue here ([] being label based for FloatIndex, while location based for IntIndex)

**Comment by jreback** [comment]
no, some of the 'other' issues are fixed (IOW, the slicing is all now consistent), e.g.

```
In [23]: s = Series(np.arange(5), index=np.arange(5) * 2.5, dtype=np.int64)

In [24]: s
Out[24]: 
0.0     0
2.5     1
5.0     2
7.5     3
10.0    4
dtype: int64

In [25]: s[2:5]
Out[25]: 
2.5    1
5.0    2
dtype: int64

In [26]: s[2.0:5.0]
Out[26]: 
2.5    1
5.0    2
dtype: int64
```

**Comment by jreback** [comment]
we should prob close this issue and open a new clarifying issue about what the problems are with FloatIndex slicing.

**Comment by jreback** [comment]
can someone parse this issue and see if we should open an issue w.r.t. float slicing?

**Comment by jorisvandenbossche** [comment]
The original reported 'issue' is still present (or better: 'debatable behaviour')

To summarize in a specific way (disregarding the .ix part of the above discussion, as that is deprecated anyway): for all index types, using integers in `[]` (`__getitem__`) is positional (like `iloc`), except for Float64Index, making this a special case. 
So also for an integer index, `[]` is positional and not label based.

I think it would be nice to make int index and float index consistent for `[]`. Making Int64Index label based would be a change with a lot of impact, changing Float64Index to do positional (when using integers, when using floats it stays label-based) would be easier I think.

**Comment by TomAugspurger** [comment]
Pushing this off 1.0.

**Comment by MarcoGorelli** [comment]
> can someone parse this issue and see if we should open an issue w.r.t. float slicing?

Looks like it's been opened here #31344

**Comment by jbrockmendel** [comment]
Reading over this thread I was briefly optimistic "with ix gone this might be easier!" but nope

> I think it would be nice to make int index and float index consistent for []. Making Int64Index label based would be a change with a lot of impact, changing Float64Index to do positional (when using integers, when using floats it stays label-based) would be easier I think.

I agree with @jorisvandenbossche here.

I'd also be on board with a "nuke it from space" option to deprecate the ambiguous behaviors
